site_name: JAX GW
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
nav:
  - "Antenna Pattern": antenna.md
